=== handelaar/oireachtas2electricbooglaloo/debatesoldXMLbackup/D/1954/Debate.dtd
<!-- Modified for single column debates FM -->
<!ELEMENT Debate (MainHeading|Line|Speaker|P|HtmlBk|Col|Miles)+>
<!ATTLIST Debate
  	House  CDATA #REQUIRED
	Vol CDATA #REQUIRED
	No CDATA #REQUIRED
	Day (Mon|Tue|Wed|Thu|Fri|Sat|Sun) #REQUIRED
	Date CDATA #REQUIRED
	Month (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) #REQUIRED
	Year CDATA #REQUIRED
	cnum CDATA #IMPLIED
	DocTitle CDATA #IMPLIED
	DateIrish CDATA #IMPLIED
	DateEnglish CDATA #IMPLIED
	CommitteeEng CDATA #IMPLIED 
	CommitteeIr CDATA #IMPLIED
	SubNameEng  CDATA #IMPLIED >

<!ENTITY % CharAttr "
  Just   (Left|Right|Center) 'Left'
  Italics (Y|N)	     #IMPLIED
  Bold    (Y|N)      #IMPLIED
  LI  CDATA      #IMPLIED
  FLI CDATA	 #IMPLIED
  BEFORE CDATA #IMPLIED"
  >

<!ENTITY aacute		"&#225;">
<!ENTITY Aacute		"&#193;">
<!ENTITY acirc		"&#226;">
<!ENTITY Acirc		"&#194;">
<!ENTITY aelig		"&#230;">
<!ENTITY AElig		"&#198;">
<!ENTITY Agrave		"&#192;">
<!ENTITY agrave		"&#224;">
<!ENTITY aring		"&#229;">
<!ENTITY Aring		"&#197;">
<!ENTITY atilde		"&#227;">
<!ENTITY Atilde		"&#195;">
<!ENTITY auml		"&#229;">
<!ENTITY Auml		"&#196;">
<!ENTITY bullet		"&#8226;">
<!ENTITY ccedil		"&#231;">
<!ENTITY bull		"&#8226;">
<!ENTITY ccaron		"&#269;">
<!ENTITY Ccedil		"&#199;">
<!ENTITY cent		"&#162;">
<!ENTITY copy		"&#169;">
<!ENTITY dagger		"&#8224;">
<!ENTITY Dagger		"&#8225;">
<!ENTITY deg		"&#176;">
<!ENTITY divide		"&#247;">
<!ENTITY eacute		"&#233;">
<!ENTITY Eacute		"&#201;">
<!ENTITY ecirc		"&#234;">
<!ENTITY Ecirc		"&#202;">
<!ENTITY egrave		"&#232;">
<!ENTITY Egrave		"&#200;">
<!ENTITY eth		"&#240;">
<!ENTITY ETH		"&#208;">
<!ENTITY emsp		"&#8195;">
<!ENTITY ensp		"&#8194;">
<!ENTITY euml		"&#235;">
<!ENTITY Euml		"&#203;">
<!ENTITY euro		"&#8364;">
<!ENTITY frac14		"&#188;">
<!ENTITY frac12		"&#189;">
<!ENTITY frac34		"&#190;">
<!ENTITY ge		"&#8805;">
<!ENTITY hellip		"&#8230;">
<!ENTITY iacute		"&#237;">
<!ENTITY Iacute		"&#205;">
<!ENTITY icirc		"&#238;">
<!ENTITY Icirc		"&#206;">
<!ENTITY igrave		"&#236;">
<!ENTITY Igrave		"&#204;">
<!ENTITY iquest		"&#191;">
<!ENTITY iuml		"&#239;">
<!ENTITY Iuml		"&#207;">
<!ENTITY lArr		"&#8656;">
<!ENTITY laquo		"&#171;">
<!ENTITY ldquo		"&#8220;">
<!ENTITY le		"&#8804;">
<!ENTITY lsquo		"&#8216;">
<!ENTITY mdash		"&#8212;">
<!ENTITY micro		"&#181;">
<!ENTITY middot		"&#183;">
<!ENTITY minus		"-">
<!ENTITY ndash		"&#8211;">
<!ENTITY ntilde		"&#241;">
<!ENTITY Ntilde		"&#209;">
<!ENTITY oacute		"&#243;">
<!ENTITY Oacute		"&#211;">
<!ENTITY ocirc		"&#244;">
<!ENTITY Ocirc		"&#212;">
<!ENTITY oelig		"&#339;">
<!ENTITY OElig		"&#338;">
<!ENTITY ograve		"&#242;">
<!ENTITY Ograve		"&#210;">
<!ENTITY oslash		"&#248;">
<!ENTITY Oslash		"&#216;">
<!ENTITY otilde		"&#245;">
<!ENTITY Otilde		"&#213;">
<!ENTITY ouml		"&#246;">
<!ENTITY Ouml		"&#214;">
<!ENTITY para		"&#182;">
<!ENTITY permil		"&#8240;">
<!ENTITY plusmn		"&#177;">
<!ENTITY pound		"&#163;">
<!ENTITY raquo		"&#187;">
<!ENTITY reg		"&#174;">
<!ENTITY rdquo		"&#8221;">
<!ENTITY rsquo		"&#8217;">
<!ENTITY scaron		"&#353;">
<!ENTITY Scaron		"&#352;">
<!ENTITY sect		"&#167;">
<!ENTITY squ		"&#9744;">
<!ENTITY sup2		"&#178;">
<!ENTITY sup3		"&#179;">
<!ENTITY szlig		"&#223;">
<!ENTITY thinsp		"&#8201;">
<!ENTITY thron		"&#254;">
<!ENTITY THORN		"&#222;">
<!ENTITY times		"&#215;">
<!ENTITY trade		"&#8482;">
<!ENTITY Uacute		"&#218;">
<!ENTITY uacute		"&#250;">
<!ENTITY ucirc		"&#251;">
<!ENTITY Ucirc		"&#219;">
<!ENTITY ugrave		"&#249;">
<!ENTITY Ugrave		"&#217;">
<!ENTITY uuml		"&#252;">
<!ENTITY Uuml		"&#220;">
<!ENTITY under		"_">
<!ENTITY yacute		"&#253;">
<!ENTITY Yacute		"&#221;">
<!ENTITY yen		"&#165;">
<!ENTITY yuml		"&#255;">
<!ENTITY Yuml		"&#376;">
<!ENTITY Zcaron		"&#382;">

<!ELEMENT br EMPTY>
<!ELEMENT tick EMPTY>
<!-- First HtmlBk should be numbered with SectId = "1" with others incrementing -->
<!ELEMENT HtmlBk EMPTY>                <!-- HtmlBk Markers identify breaks for producing straight html -->
<!ATTLIST HtmlBk 
  SectId CDATA #REQUIRED
 >

 <!ELEMENT Line EMPTY>		<!-- Horizontal Line -->
 <!ATTLIST Line
   Leading CDATA #IMPLIED
 >

<!-- Start of column indicator to be extracted from Oasys -->
<!ELEMENT Col EMPTY>
<!ATTLIST Col N CDATA #REQUIRED>

<!ELEMENT Miles EMPTY>
<!ATTLIST Miles
	com	CDATA	#REQUIRED
	par	CDATA	#IMPLIED
>

<!-- Bulk of the document is in MainHeadings and/or Sect -->
<!ELEMENT MainHeading (Line?,Title+, (Line|Sect|Speaker|Qst|TimeSt|table|P|HtmlBk|Col|Miles|Vote|Chair|adjournment)*)>
<!ATTLIST MainHeading
  Type (Prelude|OA|WA|PN|GD) "GD"
  LHead CDATA #IMPLIED
  RHead CDATA #IMPLIED
>

<!ELEMENT Sect (sTitle+, (Speaker|Line|Qst|TimeSt|table|P|HtmlBk|Col|Miles|Vote|adjournment)*)>
<!ATTLIST Sect
  LHead CDATA #IMPLIED
  RHead CDATA #IMPLIED
>

<!-- Speaker = Someone Speaking, Optional TitleTxt if name in brackets, NameTxt is their name, P's are what they said -->
<!ELEMENT Speaker (TitleTxt?, NameTxt, Location?, (P|Col|Miles|table|TimeSt|HtmlBk|img)*)> 
<!ATTLIST Speaker                              
  pid  CDATA #REQUIRED
  Who  CDATA #IMPLIED
  el   CDATA #IMPLIED
  hpid CDATA #IMPLIED
>
<!ELEMENT TitleTxt (#PCDATA|Insert|Delete|b|i|u)*> <!-- Title eg Minister for Finance -->
<!ELEMENT NameTxt (#PCDATA|Insert|Delete|b|i|u)*>  <!-- Text for speakers name, appears before : no : included) -->
<!ELEMENT Location (#PCDATA|Insert|Delete|b|i|u)*>  <!-- Speaker Constituency without brackets -->


<!ELEMENT Qst (Qid, preAsk?, asker, AskConj, askee, Col?, Quest, QRef)>
<!ATTLIST Qst
  Pid    CDATA #REQUIRED
  ToPid  CDATA #REQUIRED
  Dept   CDATA #REQUIRED
  el	 CDATA #IMPLIED
  numbered CDATA #IMPLIED
>

<!ELEMENT preAsk (#PCDATA|Col|Miles|Insert|Delete|b|i|u|sub|sup)*>  <!-- Text before asker (for Irish variant: D'fhiafraigh) -->
<!ELEMENT Qid (#PCDATA|Col|Miles|Insert|Delete|b|i|u|sub|sup)*>	<!-- Number of the question -->
<!ELEMENT asker (#PCDATA|Col|Miles|Insert|Delete|b|i|u|sub|sup)*>  <!-- Text for name of asker -->
<!ELEMENT AskConj (#PCDATA|Col|Miles|Insert|Delete|b|i|u|sub|sup)*>     <!-- " asked the " should be here (Irish variant: den) -->
<!ELEMENT askee (#PCDATA|Col|Miles|Insert|Delete|b|i|u|sub|sup)*>  <!-- Text for Askee "Minister for ..." -->
<!ELEMENT Quest (#PCDATA|Col|Miles|Deputy|Insert|Delete|b|i|u|sub|sup)*>  <!-- The actual question -->
<!ELEMENT QRef (#PCDATA|Col|Miles|Insert|Delete|b|i|u|sub|sup)*>		<!-- Question Reference -->

<!ELEMENT Deputy (Name)>  <!-- Speaker with pid attribute appearing in text -->
<!ATTLIST Deputy
  pid   CDATA #REQUIRED
>
<!ELEMENT Name (#PCDATA|Col|Miles|Insert|Delete|b|i|u|sub|sup)*>

<!ELEMENT Chair (#PCDATA|Col|Miles|Insert|Delete|b|i|u|sub|sup)*>	<!-- Who's in the chair -->
<!ATTLIST Chair
  pid   CDATA #REQUIRED
>

<!ELEMENT b (#PCDATA|Col|Miles|Insert|Delete|i|u|Deputy|br|sub|sup)*>        <!-- Bold text -->
<!ELEMENT i (#PCDATA|Col|Miles|Insert|Delete|b|u|Deputy|br|sub|sup)*>        <!-- Italic text -->
<!ELEMENT u (#PCDATA|Col|Miles|Insert|Delete|b|i|Deputy|br|sub|sup)*>        <!-- Underlined text -->
<!ELEMENT sup (#PCDATA|Col|Miles|Insert|Delete|b|u|Deputy|br|sub|i)*>
<!ELEMENT sub (#PCDATA|Col|Miles|Insert|Delete|b|u|Deputy|br|sub|i)*>
<!ELEMENT Insert (#PCDATA|Col|Miles|i|Delete|b|u|Deputy|br|sub|sup)*>        <!-- Inserted text -->
<!ELEMENT Delete (#PCDATA|Col|Miles|Insert|i|b|u|Deputy|br|sub|sup)*>        <!-- Deleted text -->

<!ELEMENT Title (#PCDATA|Col|Miles|Insert|Delete|b|i|u)*>      <!-- A paragraph title -->
<!ATTLIST Title
  el	CDATA #IMPLIED
>

<!ELEMENT sTitle (#PCDATA|Col|Miles|Insert|Delete|b|i|u)*>      <!-- A subparagraph title -->
<!ATTLIST sTitle
  el	CDATA #IMPLIED
>

<!ELEMENT P (#PCDATA|Col|Miles|Insert|Delete|b|i|u|br|sub|sup|Deputy|tick)*>      <!-- A paragraph -->
<!ATTLIST P
    %CharAttr;
	pgwide		CDATA					#IMPLIED
	el		CDATA					#IMPLIED
>

<!ELEMENT adjournment (#PCDATA|Miles|i|b|br|sub|sup)*>      <!-- An adjournment paragraph -->

<!ELEMENT TimeSt (#PCDATA)>      <!-- Timestamp e.g. "3 o'clock" no text before number please -->
<!ATTLIST TimeSt
	down	CDATA	#IMPLIED
	idown	CDATA	#IMPLIED
>


<!ELEMENT Vote (Result,YHeading,(Col|YesVote)*,NHeading,(Col|NoVote|Tellers|Decision)*)> <!-- A vote took place -->
<!ELEMENT Result (#PCDATA|Col|Miles|br)*>      <!-- e.g. "The Dail divided... -->
<!ELEMENT YHeading (#PCDATA|Col|Miles)*>    <!-- Heading for yes voters usually Ta -->
<!ELEMENT YesVote (#PCDATA|Col|Miles)*>     <!-- Person who voted yes, usually surname comma first name -->
<!ATTLIST YesVote
	pid	CDATA	#REQUIRED 
	head	CDATA	#IMPLIED >		<!-- pid = unique identifier for person in cahill database -->
<!ELEMENT NHeading (#PCDATA|Col|Miles)*>    <!-- Heading for no voters usually Nil -->
<!ELEMENT NoVote (#PCDATA|Col|Miles)*>      <!-- Person who voted no, usually surname comma first name -->
<!ATTLIST NoVote
	pid	CDATA	#REQUIRED 
	head	CDATA	#IMPLIED >		<!-- pid = unique identifier for person in cahill database -->
<!ELEMENT Tellers (#PCDATA|Col|Miles|br|sub|sup|b|i|u)*>     <!-- Text saying who counted votes -->
<!ELEMENT Decision (#PCDATA|Col|Miles|br|sub|sup|b|i|u)*>    <!-- Text giving decision as a result of vote -->

<!-- Images -->
<!ELEMENT img (#PCDATA)>
<!ATTLIST img
	websrc	CDATA	#REQUIRED 
	milessrc CDATA	#IMPLIED >	<!-- Sources Files for web and Miles added 15Feb2005 FM-->

<!-- **********************************************************-->
<!-- Subset of CALS table model                                -->
<!-- **********************************************************-->

<!ENTITY % yesorno 'NMTOKEN'> <!-- no if zero(s), yes if any other value -->
<!ENTITY % paracon '#PCDATA|P|tick|img|Col|Miles|Insert|Delete|b|i|u|br|sub|sup|Deputy'> <!-- default for use in entry content -->

<!--
The parameter entities as defined below change and simplify the CALS table
model as published (as part of the Example DTD) in MIL-HDBK-28001.  The
resulting simplified DTD has support from the SGML Open vendors and is
therefore more interoperable among different systems.

These following declarations provide the Exchange default definitions
for these entities.  However, these entities can be redefined (by giving
the appropriate parameter entity declaration(s) prior to the reference
to this Table Model declaration set entity) to fit the needs of the
current application.

Note, however, that changes may have significant effect on the ability to
interchange table information.  These changes may manifest themselves
in useability, presentation, and possible structure information degradation.
-->

<!ENTITY % tbl.table.name       "table">
<!ENTITY % tbl.table-main.mdl   "(Col|P)*,tgroup,(Col|P)*">
<!ENTITY % tbl.table.mdl        "%tbl.table-main.mdl;">
<!ENTITY % bodyatt              "">
<!ENTITY % tbl.tgroup.mdl       "colspec*,thead?,tbody?">
<!ENTITY % tbl.tgroup.att       "">
<!ENTITY % tbl.thead.att        "">
<!ENTITY % tbl.tbody.att        "">
<!ENTITY % tbl.colspec.att      "">
<!ENTITY % tbl.row.mdl          "(entry|Col|Miles)+">
<!ENTITY % tbl.row.att          "">
<!ENTITY % tbl.entry.mdl        "(%paracon;)*">
<!ENTITY % tbl.entry.att        "">

<!-- =====  Element and attribute declarations follow. =====  -->

<!--
     Default declarations previously defined in this entity and
     referenced below include:
     ENTITY % tbl.table.name       "table"
     ENTITY % tbl.table-titles.mdl "%titles;,"
     ENTITY % tbl.table.mdl        "%tbl.table-titles; tgroup+"
     ENTITY % tbl.table.att        "
                        pgwide          %yesorno;       #IMPLIED "
-->

<!ELEMENT %tbl.table.name; (%tbl.table.mdl;)>

<!ATTLIST %tbl.table.name;
        frame           (top|bottom|topbot|all|sides|none)      #IMPLIED
	measure		CDATA					#IMPLIED
        colsep          %yesorno;                               #IMPLIED
        rowsep          %yesorno;                               #IMPLIED
	pgwide		CDATA					#IMPLIED
	fontsize	CDATA					#IMPLIED
	el		CDATA					#IMPLIED
        %bodyatt;
>

<!--
     Default declarations previously defined in this entity and
     referenced below include:
     ENTITY % tbl.tgroup.mdl    "colspec*,thead?,tbody"
     ENTITY % tbl.tgroup.att    ""
-->

<!ELEMENT tgroup (%tbl.tgroup.mdl;) >

<!ATTLIST tgroup
        cols            NMTOKEN                                 #REQUIRED
        colsep          %yesorno;                               #IMPLIED
        rowsep          %yesorno;                               #IMPLIED
        align           (left|right|center|justify|char)        #IMPLIED
        %tbl.tgroup.att;
>

<!--
     Default declarations previously defined in this entity and
     referenced below include:
     ENTITY % tbl.colspec.att   ""
-->

<!ELEMENT colspec EMPTY >

<!ATTLIST colspec
        colnum          NMTOKEN                                 #IMPLIED
        colname         NMTOKEN                                 #IMPLIED
        colwidth        CDATA                                   #IMPLIED
        colsep          %yesorno;                               #IMPLIED
        rowsep          %yesorno;                               #IMPLIED
        align           (left|right|center|justify|char)        #IMPLIED
	valign		(top|bottom|middle)			#IMPLIED
        char            CDATA                                   #IMPLIED
	rpad		CDATA					#IMPLIED
	lpad		CDATA					#IMPLIED
        charoff         NMTOKEN                                 #IMPLIED
        %tbl.colspec.att;
>

<!--
     Default declarations previously defined in this entity and
     referenced below include:
     ENTITY % tbl.thead.att      ""
-->

<!ELEMENT thead (row|Col|Miles)+>

<!ATTLIST thead
        valign          (top|middle|bottom)                     #IMPLIED
        %tbl.thead.att;
>

<!--
     Default declarations previously defined in this entity and
     referenced below include:
     ENTITY % tbl.tbody.att     ""
-->

<!ELEMENT tbody (row|Col|Miles)+>

<!ATTLIST tbody
        valign          (top|middle|bottom)                     #IMPLIED
        %tbl.tbody.att;
>

<!--
     Default declarations previously defined in this entity and
     referenced below include:
     ENTITY % tbl.row.mdl       "entry+"
     ENTITY % tbl.row.att       ""
-->

<!ELEMENT row (%tbl.row.mdl;)>

<!ATTLIST row
        rowsep          %yesorno;                               #IMPLIED
        valign          (top|middle|bottom)                     #IMPLIED
        %tbl.row.att;
>


<!--
     Default declarations previously defined in this entity and
     referenced below include:
     ENTITY % paracon           "#PCDATA"
     ENTITY % tbl.entry.mdl     "(%paracon;)*"
     ENTITY % tbl.entry.att     ""
-->

<!ELEMENT entry %tbl.entry.mdl;>

<!ATTLIST entry
        colname         NMTOKEN                                 #IMPLIED
        namest          NMTOKEN                                 #IMPLIED
        nameend         NMTOKEN                                 #IMPLIED
        morerows        NMTOKEN                                 #IMPLIED
        colsep          %yesorno;                               #IMPLIED
        rowsep          %yesorno;                               #IMPLIED
        align           (left|right|center|justify|char)        #IMPLIED
        char            CDATA                                   #IMPLIED
        charoff         NMTOKEN                                 #IMPLIED
	rpad		CDATA					#IMPLIED
	lpad		CDATA					#IMPLIED
        valign          (top|middle|bottom)                     #IMPLIED
        %tbl.entry.att;
>

=== handelaar/oireachtas2electricbooglaloo/debatesoldXMLbackup/S/1927/SEN19271202.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Debate SYSTEM "../Debate.dtd"[]>
<Debate DocTitle="Seanad Debate" Day="Fri" Date="2" Month="Dec" Year="1927" Vol="10" No="6" DateIrish="Dé hAoine, 2 Nollaig 1927" DateEnglish="Friday, 2 December 1927" House="S" CommitteeEng="" CommitteeIr="" SubNameEng="" cnum="183">
  <MainHeading Type="Prelude" LHead="" RHead="">
    <Title>
    </Title>
    <P>
      <Col N="183" /> Do chuaidh an Cathaoirleach i gceannas ar 12 meadhon lae.</P>
  </MainHeading>
  <MainHeading Type="GD" LHead="PRIVATE BUSINESS. - PILOTAGE ORDER CONFIRMATION" RHead="(No. 2) BILL, 1927&mdash;FIFTH STAGE">
    <Title>PRIVATE BUSINESS. - PILOTAGE ORDER CONFIRMATION (No. 2) BILL, 1927&mdash;FIFTH STAGE.</Title>
    <P>Motion made&mdash;That this Bill be received for final consideration and do now pass.&mdash;(Senator Bennett.)</P>
    <P>Question put and agreed to.</P>
  </MainHeading>
  <MainHeading Type="GD" LHead="PUBLIC BUSINESS. - LOCAL ELECTIONS" RHead="BILL, 1927&mdash;REPORT STAGE">
    <Title>PUBLIC BUSINESS. - LOCAL ELECTIONS BILL, 1927&mdash;REPORT STAGE.</Title>
    <Speaker pid="" hpid="CATHAOIRLEACH CATHAOIRLEACH">
      <NameTxt>CATHAOIRLEACH</NameTxt>
      <P>There were no amendments in Committee to this Bill, and no amendments have been tabled for the Report Stage.</P>
      <P>Motion made&mdash;That the Bill be received on Report.</P>
      <P>Question put and agreed to.</P>
    </Speaker>
  </MainHeading>
  <MainHeading Type="GD" LHead="PUBLIC BUSINESS. - DEFENCE FORCES (TEMPORARY" RHead="PROVISIONS) (No. 2) BILL, 1927&mdash;REPORT STAGE">
    <Title>PUBLIC BUSINESS. - DEFENCE FORCES (TEMPORARY PROVISIONS) (No. 2) BILL, 1927&mdash;REPORT STAGE.</Title>
    <P>Motion made&mdash;That the Bill be received on Report.</P>
    <P>Question put and agreed to.</P>
  </MainHeading>
  <MainHeading Type="GD" LHead="PUBLIC BUSINESS. - FINANCE (No." RHead="2) BILL, 1927&mdash;REPORT STAGE">
    <Title>PUBLIC BUSINESS. - FINANCE (No. 2) BILL, 1927&mdash;REPORT STAGE.</Title>
    <Speaker pid="" hpid="CATHAOIRLEACH CATHAOIRLEACH">
      <NameTxt>CATHAOIRLEACH</NameTxt>
      <P>This Bill has been certified by the Ceann Comhairle of the Dáil as a Money Bill.</P>
      <P>Motion made&mdash;That the Bill be received on Report.</P>
      <P>Question put and agreed to.</P>
    </Speaker>
  </MainHeading>
  <MainHeading Type="GD" LHead="PUBLIC BUSINESS. - SUSPENSION" RHead="OF STANDING ORDERS">
    <Title>PUBLIC BUSINESS. - SUSPENSION OF STANDING ORDERS.</Title>
    <Speaker pid="EdwardBellinghamBart" hpid="Sir HENRY BELLINGHAM Sir HENRY BELLINGHAM">
      <NameTxt>Sir HENRY BELLINGHAM</NameTxt>
      <P>On behalf of Senator Guinness, I move:&mdash;<Col N="184" />&ldquo;That the Standing Orders be suspended for the purpose of enabling the Fifth Stage of the following Bills to be taken to-day, Friday, 2nd December, 1927:&mdash;Local Elections Bill, 1927, Defence Forces (Temporary Provisions) (No. 2) Bill, 1927, and the Finance (No. 2) Bill, 1927.&rdquo;</P>
    </Speaker>
    <Speaker pid="WilliamBarrington" hpid="Mr. BARRINGTON Mr. BARRINGTON">
      <NameTxt>Mr. BARRINGTON</NameTxt>
      <P>I second the motion.</P>
      <P>Question put and agreed to.</P>
      <P>Standing Orders suspended.</P>
    </Speaker>
  </MainHeading>
  <MainHeading Type="GD" LHead="PUBLIC BUSINESS. - LOCAL ELECTIONS" RHead="BILL, 1927&mdash;FIFTH STAGE">
    <Title>PUBLIC BUSINESS. - LOCAL ELECTIONS BILL, 1927&mdash;FIFTH STAGE.</Title>
    <P>Motion made&mdash;That the Bill be received for final consideration and do now pass.</P>
    <P>Question put and agreed to.</P>
  </MainHeading>
  <MainHeading Type="GD" LHead="PUBLIC BUSINESS. - DEFENCE FORCES (TEMPORARY" RHead="PROVISIONS) (No. 2) BILL, 1927&mdash;FIFTH STAGE">
    <Title>PUBLIC BUSINESS. - DEFENCE FORCES (TEMPORARY PROVISIONS) (No. 2) BILL, 1927&mdash;FIFTH STAGE.</Title>
    <P>Motion made&mdash;That the Bill be received for final consideration and do now pass.</P>
    <P>Question put and agreed to.</P>
  </MainHeading>
  <MainHeading Type="GD" LHead="PUBLIC BUSINESS. - FINANCE (No." RHead="2) BILL, 1927&mdash;FIFTH STAGE">
    <Title>PUBLIC BUSINESS. - FINANCE (No. 2) BILL, 1927&mdash;FIFTH STAGE.</Title>
    <P>Motion made&mdash;That the Bill be received for final consideration and do now pass.</P>
    <P>Question put and agreed to.</P>
  </MainHeading>
  <MainHeading Type="GD" LHead="PUBLIC BUSINESS. -" RHead="THE ADJOURNMENT">
    <Title>PUBLIC BUSINESS. - THE ADJOURNMENT.</Title>
    <Speaker pid="" hpid="CATHAOIRLEACH CATHAOIRLEACH">
      <NameTxt>CATHAOIRLEACH</NameTxt>
      <P>As matters at present stand it will not be necessary for the Seanad to meet again before the 15th February next.  In the event of any contingency arising which would render a meeting of the House necessary, a meeting will be duly convened on proper notice.</P>
      <P>The Seanad adjourned at 12.10 p.m.</P>
    </Speaker>
  </MainHeading>
</Debate>
